### PR TITLE
show warning only if verbose is set; no ways to suppress it on JRuby

### PR DESCRIPTION
**Pull request by cielavenir**

### CODE REVIEW

**Comment by cielavenir** [comment]
RDoc example?

== NOTE:
- Recently (perhaps from July 2013), Chrome WebStore started to deny PKCS1 private keys.
- From crxmake 2.1.3, newly generated keys are written in PKCS8, if openssl_pkcs8 gem is installed.
- Existing keys can be converted using:

```
    Dir.glob(dir+'/*.pem').each{|e|
        key=OpenSSL::PKey::RSA.new(File.read(e))
        File.open(e,'wb'){|f|f<<key.to_pem_pkcs8}
    }
```

**Comment by cielavenir** [comment]
I have two more suggestions:
- Generate key to @pkey if it doesn't exist
- Use Zip::ZipOutputStream::write_buffer to avoid temporary zip (especially for crx)

These will go to other issues.

**Comment by Constellation** [comment]
Looks nice. merging.

**Comment by Constellation** [comment]
Thanks :)

**Pull request merged**
