### PR TITLE
Updated for rubyzip 1.0.0

### PR DESCRIPTION
**Pull request by cielavenir**

### CODE REVIEW

**Comment by Constellation** [comment]
lgtm. merging, thanks :)

**Comment by galfert** [comment]
Maybe I'm missing something, but don't you have to set the dependency in the gemspec to rubyzip as well then?

**Comment by Constellation** [comment]
Oops. Nice catch. I'll fix it soon.

**Comment by Constellation** [comment]
I've fixed and published 2.2.0. Thanks.

**Comment by cielavenir** [comment]
Oh, when I saw https://github.com/Constellation/crxmake/pull/7, I didn't know gemspec was still old...

**Comment by Constellation** [comment]
@cielavenir:
Don't mind, it's my mistake :D

**Pull request merged**
